name: Merge tag or branch into master

on:
  workflow_call:

jobs:
  merge:
    name: Merge '${{ github.ref }}' into master
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "match=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Merge branch
        if: steps.check-tag.outputs.match == 'true'
        uses: julbme/gh-action-merge-branch@v1
        with:
          from: ${{ github.ref }}
          to: master
          message: Merge ${{ github.ref }} into master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_MANAGERS_TOKEN }}
